//
//  LiveVisionPipelineTests.swift
//  AssembleAITests
//

import XCTest
import CoreMedia
import CoreVideo
import UIKit
@testable import AssembleAI

@MainActor
final class LiveVisionPipelineTests: XCTestCase {
    
    private var visionService: VisionService!
    private var cameraService: CameraService!
    
    @MainActor
    override func setUp() {
        super.setUp()
        visionService = VisionService()
        cameraService = CameraService()
    }
    
    @MainActor
    override func tearDown() {
        visionService = nil
        cameraService = nil
        super.tearDown()
    }
    
    // MARK: - Test 1: Direct PixelBuffer Vision Analysis
    @MainActor
    func testPixelBufferVisionAnalysis() async throws {
        // Use high-quality synthetic breadboard circuit frame generated by CameraService
        guard let pixelBuffer = cameraService.createSimulatorPixelBuffer() else {
            XCTFail("Failed to create synthetic test pixel buffer")
            return
        }
        
        let timestamp = CMTime(seconds: 123.456, preferredTimescale: 600)
        let observation = try await visionService.analyze(frame: pixelBuffer, orientation: .up, timestamp: timestamp)
        
        XCTAssertGreaterThan(observation.imageSize.width, 0)
        XCTAssertGreaterThan(observation.imageSize.height, 0)
        XCTAssertGreaterThan(observation.processingTimeMs, 0)
        
        // Check that OCR extracted the text from the test image ("220 OHM RESISTOR R1" or similar)
        XCTAssertFalse(observation.detectedText.isEmpty, "Vision OCR should detect text in synthetic test frame")
        let recognizedString = observation.detectedText.map { $0.text }.joined(separator: " ")
        XCTAssertTrue(recognizedString.localizedCaseInsensitiveContains("220") || recognizedString.localizedCaseInsensitiveContains("RESISTOR") || recognizedString.localizedCaseInsensitiveContains("AssembleAI"))
        
        let metrics = await visionService.getMetrics()
        XCTAssertEqual(metrics.requestsStarted, 1)
        XCTAssertEqual(metrics.requestsCompleted, 1)
    }
    
    // MARK: - Test 2: Observation Stream End-to-End Execution
    func testObservationStreamPipeline() async throws {
        let (sampledStream, sampledContinuation) = AsyncStream.makeStream(of: SampledFrame.self)
        let observationStream = visionService.observationStream(from: sampledStream)
        
        let mockService = MockVisionService(simulatedLatencyMs: 10.0)
        let scriptedObs1 = VisualObservation(
            imageSize: CGSize(width: 100, height: 100),
            detectedText: [DetectedText(text: "Frame 1 Text", confidence: 0.9, boundingBox: .zero)],
            regions: [],
            processingTimeMs: 10.0
        )
        let scriptedObs2 = VisualObservation(
            imageSize: CGSize(width: 100, height: 100),
            detectedText: [DetectedText(text: "Frame 2 Text", confidence: 0.95, boundingBox: .zero)],
            regions: [],
            processingTimeMs: 10.0
        )
        mockService.setScriptedObservations([scriptedObs1, scriptedObs2])
        
        let mockObservationStream = mockService.observationStream(from: sampledStream)
        
        var receivedObservations: [VisualObservation] = []
        
        let consumerTask = Task {
            for await obs in mockObservationStream {
                receivedObservations.append(obs)
                if receivedObservations.count >= 2 {
                    break
                }
            }
        }
        
        let testBuffer = createSolidColorPixelBuffer(color: .white)
        sampledContinuation.yield(SampledFrame(pixelBuffer: testBuffer, sequenceNumber: 1))
        sampledContinuation.yield(SampledFrame(pixelBuffer: testBuffer, sequenceNumber: 2))
        
        _ = await consumerTask.result
        sampledContinuation.finish()
        
        XCTAssertEqual(receivedObservations.count, 2)
        XCTAssertEqual(receivedObservations.first?.detectedText.first?.text, "Frame 1 Text")
        XCTAssertEqual(receivedObservations.last?.detectedText.first?.text, "Frame 2 Text")
    }
    
    // MARK: - Test 3: Empty Scene Behavior (No False Hallucinations)
    func testEmptySceneProducesEmptyObservation() async throws {
        let solidBlankBuffer = createSolidColorPixelBuffer(color: .black)
        let observation = try await visionService.analyze(frame: solidBlankBuffer, orientation: .up)
        
        XCTAssertTrue(observation.detectedText.isEmpty, "Blank image should produce zero detected text")
        XCTAssertEqual(observation.regions.count, 0, "Blank image should produce zero component regions")
    }
    
    // MARK: - Test 4: Task Cancellation Safety
    func testVisionTaskCancellation() async {
        let solidBuffer = createSolidColorPixelBuffer(color: .white)
        
        let task = Task {
            try await visionService.analyze(frame: solidBuffer)
        }
        
        task.cancel()
        let result = await task.result
        
        switch result {
        case .success(let obs):
            // If it completed before cancellation check, it's valid
            XCTAssertNotNil(obs)
        case .failure(let error):
            // Cancellation error or domain error is expected
            XCTAssertNotNil(error)
        }
    }
    
    // MARK: - Test 5: Manual Photo Workflow Regression Guard (UIImage)
    @MainActor
    func testManualPhotoImageAnalysisWorkflowPreserved() async throws {
        let testImage = cameraService.createSimulatorTestImage()
        let observation = try await visionService.analyze(image: testImage)
        
        XCTAssertGreaterThan(observation.imageSize.width, 0)
        XCTAssertGreaterThan(observation.imageSize.height, 0)
        XCTAssertFalse(observation.detectedText.isEmpty, "Manual image analysis should extract OCR text")
    }
    
    // MARK: - Test 6: Mock Vision Sequence Verification
    func testMockVisionScriptedSequence() async throws {
        let mock = MockVisionService(simulatedLatencyMs: 0)
        
        let obs1 = VisualObservation(imageSize: .zero, detectedText: [DetectedText(text: "resistor_missing", confidence: 0.8, boundingBox: .zero)], regions: [], processingTimeMs: 0)
        let obs2 = VisualObservation(imageSize: .zero, detectedText: [DetectedText(text: "resistor_placed_row14", confidence: 0.85, boundingBox: .zero)], regions: [], processingTimeMs: 0)
        let obs3 = VisualObservation(imageSize: .zero, detectedText: [DetectedText(text: "resistor_placed_row15", confidence: 0.96, boundingBox: .zero)], regions: [], processingTimeMs: 0)
        
        mock.setScriptedObservations([obs1, obs2, obs3])
        
        let dummyImage = UIImage()
        let r1 = try await mock.analyze(image: dummyImage)
        let r2 = try await mock.analyze(image: dummyImage)
        let r3 = try await mock.analyze(image: dummyImage)
        
        XCTAssertEqual(r1.detectedText.first?.text, "resistor_missing")
        XCTAssertEqual(r2.detectedText.first?.text, "resistor_placed_row14")
        XCTAssertEqual(r3.detectedText.first?.text, "resistor_placed_row15")
    }
    
    // MARK: - Helpers
    
    private func createSolidColorPixelBuffer(color: UIColor, size: CGSize = CGSize(width: 128, height: 128)) -> CVPixelBuffer {
        var pixelBuffer: CVPixelBuffer?
        let options: [CFString: Any] = [
            kCVPixelBufferCGImageCompatibilityKey: true,
            kCVPixelBufferCGBitmapContextCompatibilityKey: true
        ]
        
        let status = CVPixelBufferCreate(
            kCFAllocatorDefault,
            Int(size.width),
            Int(size.height),
            kCVPixelFormatType_32BGRA,
            options as CFDictionary,
            &pixelBuffer
        )
        
        guard status == kCVReturnSuccess, let buffer = pixelBuffer else {
            fatalError("Failed to allocate test pixel buffer")
        }
        
        CVPixelBufferLockBaseAddress(buffer, [])
        defer { CVPixelBufferUnlockBaseAddress(buffer, []) }
        
        guard let pxdata = CVPixelBufferGetBaseAddress(buffer) else {
            fatalError("Failed to access base address")
        }
        
        let bytesPerRow = CVPixelBufferGetBytesPerRow(buffer)
        let rgbColorSpace = CGColorSpaceCreateDeviceRGB()
        guard let context = CGContext(
            data: pxdata,
            width: Int(size.width),
            height: Int(size.height),
            bitsPerComponent: 8,
            bytesPerRow: bytesPerRow,
            space: rgbColorSpace,
            bitmapInfo: CGImageAlphaInfo.premultipliedFirst.rawValue | CGBitmapInfo.byteOrder32Little.rawValue
        ) else {
            fatalError("Failed to create CGContext")
        }
        
        context.setFillColor(color.cgColor)
        context.fill(CGRect(origin: .zero, size: size))
        
        return buffer
    }
}
